### ISSUE TITLE
PLEASE UPLOAD THE SOURCE!!!

### ISSUE THREAD

**Issue by Thundros** [nyashafrank/ThreeJS-Weather-Simulator#1]
Hi, I would REALLY like to try this! PLEASE upload the source code! Thank you so kindly!

**Comment by nyashafrank** [comment]
Hello! This simulator is for a school project, so it's not fully completed as I just started it. The only thing that is working is the thunderstorm. But I can upload what I have so far :)

**Comment by nyashafrank** [comment]
Just uploaded!

**Comment by Thundros** [comment]
PLEASE keep uploading this! I am extremely interested in this project! <3
